WIFI_SSID = 'XXXXXXX'
WIFI_PASS = 'XXXXXXX'

DATACAKE_TOKEN = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
DATACAKE_MQTT_URL = 'mqtt.datacake.co'
DATACAKE_MQTT_PORT = 1883
DATACAKE_DEVICE_ID = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
DATACAKE_MQTT_TOPIC = 'XXXXXXX'
